fragment PostParts on Post {
  __typename
  title
  subtitle
  author
  date
  slug
  image
  desc
  body
}

fragment PageParts on Page {
  __typename
  title
  author
  date
  body
}

fragment GruppenParts on Gruppen {
  __typename
  title
  author
  date
  body
}

fragment GlobalParts on Global {
  __typename
  header {
    __typename
    nav {
      __typename
      label
      link
      icon
      color
      links {
        __typename
        label
        link
        icon
        color
      }
    }
  }
  footer {
    __typename
    social {
      __typename
      facebook
      instagram
    }
    columns {
      __typename
      title
      links {
        __typename
        text
        url
        external
      }
    }
  }
}
